
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 17 12:02:12 CEST 2011
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Collection;
import java.util.Iterator;
import java.util.Calendar;
import manager.*;
import command.*;

/** CUP v0.10k generated parser.
  * @version Wed Aug 17 12:02:12 CEST 2011
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\141\000\002\002\004\000\002\003\002\000\002\003" +
    "\003\000\002\024\005\000\002\037\004\000\002\040\004" +
    "\000\002\011\003\000\002\011\004\000\002\004\004\000" +
    "\002\004\004\000\002\004\004\000\002\004\004\000\002" +
    "\004\004\000\002\004\004\000\002\004\004\000\002\004" +
    "\005\000\002\004\004\000\002\004\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\004\000\002\007\004\000" +
    "\002\010\005\000\002\010\003\000\002\006\004\000\002" +
    "\006\004\000\002\026\005\000\002\026\005\000\002\026" +
    "\005\000\002\026\005\000\002\026\005\000\002\026\005" +
    "\000\002\026\004\000\002\026\003\000\002\026\005\000" +
    "\002\026\004\000\002\030\003\000\002\030\003\000\002" +
    "\035\003\000\002\035\003\000\002\035\003\000\002\035" +
    "\003\000\002\005\004\000\002\005\004\000\002\005\004" +
    "\000\002\005\004\000\002\005\003\000\002\036\003\000" +
    "\002\036\004\000\002\036\003\000\002\036\004\000\002" +
    "\034\003\000\002\034\003\000\002\034\003\000\002\020" +
    "\004\000\002\020\004\000\002\020\004\000\002\020\004" +
    "\000\002\020\006\000\002\021\003\000\002\021\003\000" +
    "\002\021\005\000\002\021\004\000\002\015\002\000\002" +
    "\015\003\000\002\022\003\000\002\022\005\000\002\023" +
    "\006\000\002\023\006\000\002\041\003\000\002\041\003" +
    "\000\002\025\003\000\002\025\003\000\002\025\003\000" +
    "\002\025\003\000\002\025\003\000\002\025\003\000\002" +
    "\025\003\000\002\017\003\000\002\017\003\000\002\043" +
    "\005\000\002\042\003\000\002\042\004\000\002\042\005" +
    "\000\002\042\005\000\002\014\007\000\002\046\007\000" +
    "\002\046\004\000\002\027\003\000\002\027\003\000\002" +
    "\027\003\000\002\027\003\000\002\031\010\000\002\033" +
    "\003\000\002\033\003\000\002\044\005\000\002\045\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\230\000\064\002\000\005\026\006\006\007\052\010" +
    "\005\011\007\015\012\020\054\021\056\022\022\023\042" +
    "\046\017\047\020\052\030\054\053\060\033\061\040\066" +
    "\035\067\004\071\023\072\036\073\031\074\010\075\057" +
    "\077\051\001\002\000\004\026\232\001\002\000\026\024" +
    "\uffd2\026\uffd2\027\uffd2\033\uffd2\034\uffd2\035\uffd2\062\231" +
    "\063\uffd2\064\uffd2\072\uffd2\001\002\000\022\024\uffcd\026" +
    "\uffcd\027\uffcd\033\uffcd\034\uffcd\035\uffcd\063\uffcd\064\uffcd" +
    "\001\002\000\030\046\017\047\066\052\030\054\053\060" +
    "\033\061\040\071\023\073\031\074\010\075\057\077\051" +
    "\001\002\000\052\004\uffb8\012\uffb8\024\uffb8\026\uffb8\027" +
    "\uffb8\033\uffb8\034\uffb8\035\uffb8\037\uffb8\041\uffb8\042\uffb8" +
    "\044\uffb8\045\uffb8\047\uffb8\053\uffb8\054\uffb8\055\uffb8\056" +
    "\uffb8\057\uffb8\072\uffb8\001\002\000\010\011\uffee\015\uffee" +
    "\072\uffee\001\002\000\012\025\163\047\167\073\166\074" +
    "\165\001\002\000\010\011\007\015\012\072\217\001\002" +
    "\000\004\002\214\001\002\000\022\004\204\024\105\026" +
    "\113\027\107\033\uffc2\034\110\035\104\072\203\001\002" +
    "\000\064\002\uffff\005\026\006\006\007\052\010\005\011" +
    "\007\015\012\020\054\021\056\022\022\023\042\046\017" +
    "\047\020\052\030\054\053\060\033\061\040\066\035\067" +
    "\004\071\023\072\036\073\031\074\010\075\057\077\051" +
    "\001\002\000\030\046\064\047\066\052\030\054\053\060" +
    "\033\061\040\071\023\073\031\074\010\075\057\077\051" +
    "\001\002\000\024\037\uffdd\040\063\041\uffdd\042\uffdd\054" +
    "\uffdd\055\uffdd\056\uffdd\057\uffdd\072\uffea\001\002\000\006" +
    "\013\174\014\173\001\002\000\022\024\uffce\026\uffce\027" +
    "\uffce\033\uffce\034\uffce\035\uffce\063\uffce\064\uffce\001\002" +
    "\000\052\004\uffb7\012\uffb7\024\uffb7\026\uffb7\027\uffb7\033" +
    "\uffb7\034\uffb7\035\uffb7\037\uffb7\041\uffb7\042\uffb7\044\uffb7" +
    "\045\uffb7\047\uffb7\053\uffb7\054\uffb7\055\uffb7\056\uffb7\057" +
    "\uffb7\072\uffb7\001\002\000\004\072\172\001\002\000\020" +
    "\037\137\041\074\042\067\054\070\055\073\056\071\057" +
    "\072\001\002\000\016\024\105\026\113\027\107\033\uffc2" +
    "\034\110\035\104\001\002\000\062\005\026\006\006\007" +
    "\052\010\005\011\007\015\012\020\054\021\056\022\022" +
    "\023\042\046\017\047\020\052\030\054\053\060\033\061" +
    "\040\066\035\067\004\071\023\072\036\073\031\074\010" +
    "\075\057\077\051\001\002\000\030\046\064\047\066\052" +
    "\030\054\053\060\033\061\040\071\023\073\031\074\010" +
    "\075\057\077\051\001\002\000\052\004\uffb9\012\uffb9\024" +
    "\uffb9\026\uffb9\027\uffb9\033\uffb9\034\uffb9\035\uffb9\037\uffb9" +
    "\041\uffb9\042\uffb9\044\uffb9\045\uffb9\047\uffb9\053\uffb9\054" +
    "\uffb9\055\uffb9\056\uffb9\057\uffb9\072\uffb9\001\002\000\006" +
    "\047\062\072\151\001\002\000\052\004\uffb5\012\uffb5\024" +
    "\uffb5\026\uffb5\027\uffb5\033\uffb5\034\uffb5\035\uffb5\037\uffb5" +
    "\041\uffb5\042\uffb5\044\uffb5\045\uffb5\047\uffb5\053\uffb5\054" +
    "\uffb5\055\uffb5\056\uffb5\057\uffb5\072\uffb5\001\002\000\004" +
    "\072\147\001\002\000\004\026\146\001\002\000\072\002" +
    "\ufff0\005\ufff0\006\ufff0\007\ufff0\010\ufff0\011\ufff0\013\ufff0" +
    "\014\ufff0\015\ufff0\016\ufff0\020\ufff0\021\ufff0\022\ufff0\023" +
    "\ufff0\046\ufff0\047\ufff0\052\ufff0\054\ufff0\060\ufff0\061\ufff0" +
    "\066\ufff0\067\ufff0\071\ufff0\072\ufff0\073\ufff0\074\ufff0\075" +
    "\ufff0\077\ufff0\001\002\000\016\024\105\026\113\027\107" +
    "\033\uffc2\034\110\035\104\001\002\000\052\004\uffb6\012" +
    "\uffb6\024\uffb6\026\uffb6\027\uffb6\033\uffb6\034\uffb6\035\uffb6" +
    "\037\uffb6\041\uffb6\042\uffb6\044\uffb6\045\uffb6\047\uffb6\053" +
    "\uffb6\054\uffb6\055\uffb6\056\uffb6\057\uffb6\072\uffb6\001\002" +
    "\000\034\012\uffdc\037\uffdc\041\uffdc\042\uffdc\044\uffdc\045" +
    "\uffdc\047\uffdc\053\uffdc\054\uffdc\055\uffdc\056\uffdc\057\uffdc" +
    "\072\uffdc\001\002\000\030\046\064\047\066\052\030\054" +
    "\053\060\033\061\040\071\023\073\031\074\010\075\057" +
    "\077\051\001\002\000\004\072\141\001\002\000\034\012" +
    "\uffe0\037\uffe0\041\uffe0\042\uffe0\044\uffe0\045\uffe0\047\uffe0" +
    "\053\uffe0\054\uffe0\055\uffe0\056\uffe0\057\uffe0\072\uffe0\001" +
    "\002\000\012\012\uffb0\044\uffb0\045\uffb0\072\uffb0\001\002" +
    "\000\010\044\131\045\132\072\134\001\002\000\020\024" +
    "\uffd3\026\uffd3\027\uffd3\033\uffd3\034\uffd3\035\uffd3\072\uffd3" +
    "\001\002\000\010\011\uffef\015\uffef\072\uffef\001\002\000" +
    "\052\004\uffb4\012\uffb4\024\uffb4\026\uffb4\027\uffb4\033\uffb4" +
    "\034\uffb4\035\uffb4\037\uffb4\041\uffb4\042\uffb4\044\uffb4\045" +
    "\uffb4\047\uffb4\053\uffb4\054\uffb4\055\uffb4\056\uffb4\057\uffb4" +
    "\072\uffb4\001\002\000\022\024\uffcc\026\uffcc\027\uffcc\033" +
    "\uffcc\034\uffcc\035\uffcc\063\uffcc\064\uffcc\001\002\000\030" +
    "\046\064\047\066\052\030\054\053\060\033\061\040\071" +
    "\023\073\031\074\010\075\057\077\051\001\002\000\026" +
    "\024\uffd0\026\uffd0\027\uffd0\030\127\033\uffd0\034\uffd0\035" +
    "\uffd0\063\uffd0\064\uffd0\072\uffd0\001\002\000\020\024\105" +
    "\026\113\027\107\033\uffc2\034\110\035\104\072\114\001" +
    "\002\000\004\047\062\001\002\000\052\004\uffba\012\uffba" +
    "\024\uffba\026\uffba\027\uffba\033\uffba\034\uffba\035\uffba\037" +
    "\uffba\041\uffba\042\uffba\044\uffba\045\uffba\047\uffba\053\uffba" +
    "\054\uffba\055\uffba\056\uffba\057\uffba\072\uffba\001\002\000" +
    "\072\002\ufffb\005\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb" +
    "\013\ufffb\014\ufffb\015\ufffb\016\ufffb\020\ufffb\021\ufffb\022" +
    "\ufffb\023\ufffb\046\ufffb\047\ufffb\052\ufffb\054\ufffb\060\ufffb" +
    "\061\ufffb\066\ufffb\067\ufffb\071\ufffb\072\ufffb\073\ufffb\074" +
    "\ufffb\075\ufffb\077\ufffb\001\002\000\006\047\uffe9\072\uffe9" +
    "\001\002\000\010\040\063\047\uffea\072\uffea\001\002\000" +
    "\030\046\064\047\066\052\030\054\053\060\033\061\040" +
    "\071\023\073\031\074\010\075\057\077\051\001\002\000" +
    "\030\046\064\047\066\052\030\054\053\060\033\061\040" +
    "\071\023\073\031\074\010\075\057\077\051\001\002\000" +
    "\022\041\074\042\067\047\uffeb\054\070\055\073\056\071" +
    "\057\072\072\uffeb\001\002\000\034\012\uffdd\037\uffdd\041" +
    "\uffdd\042\uffdd\044\uffdd\045\uffdd\047\uffdd\053\uffdd\054\uffdd" +
    "\055\uffdd\056\uffdd\057\uffdd\072\uffdd\001\002\000\030\046" +
    "\064\047\066\052\030\054\053\060\033\061\040\071\023" +
    "\073\031\074\010\075\057\077\051\001\002\000\030\046" +
    "\064\047\066\052\030\054\053\060\033\061\040\071\023" +
    "\073\031\074\010\075\057\077\051\001\002\000\030\046" +
    "\064\047\066\052\030\054\053\060\033\061\040\071\023" +
    "\073\031\074\010\075\057\077\051\001\002\000\030\046" +
    "\064\047\066\052\030\054\053\060\033\061\040\071\023" +
    "\073\031\074\010\075\057\077\051\001\002\000\030\046" +
    "\064\047\066\052\030\054\053\060\033\061\040\071\023" +
    "\073\031\074\010\075\057\077\051\001\002\000\030\046" +
    "\064\047\066\052\030\054\053\060\033\061\040\071\023" +
    "\073\031\074\010\075\057\077\051\001\002\000\034\012" +
    "\uffe3\037\uffe3\041\uffe3\042\uffe3\044\uffe3\045\uffe3\047\uffe3" +
    "\053\uffe3\054\uffe3\055\uffe3\056\uffe3\057\uffe3\072\uffe3\001" +
    "\002\000\034\012\uffe5\037\uffe5\041\074\042\uffe5\044\uffe5" +
    "\045\uffe5\047\uffe5\053\uffe5\054\uffe5\055\uffe5\056\071\057" +
    "\072\072\uffe5\001\002\000\034\012\uffe6\037\uffe6\041\uffe6" +
    "\042\uffe6\044\uffe6\045\uffe6\047\uffe6\053\uffe6\054\uffe6\055" +
    "\uffe6\056\uffe6\057\uffe6\072\uffe6\001\002\000\034\012\uffe7" +
    "\037\uffe7\041\uffe7\042\uffe7\044\uffe7\045\uffe7\047\uffe7\053" +
    "\uffe7\054\uffe7\055\uffe7\056\uffe7\057\uffe7\072\uffe7\001\002" +
    "\000\034\012\uffe4\037\uffe4\041\074\042\uffe4\044\uffe4\045" +
    "\uffe4\047\uffe4\053\uffe4\054\uffe4\055\uffe4\056\071\057\072" +
    "\072\uffe4\001\002\000\034\012\uffe2\037\uffe2\041\074\042" +
    "\uffe2\044\uffe2\045\uffe2\047\uffe2\053\uffe2\054\uffe2\055\uffe2" +
    "\056\071\057\072\072\uffe2\001\002\000\034\012\uffde\037" +
    "\uffde\041\uffde\042\uffde\044\uffde\045\uffde\047\uffde\053\uffde" +
    "\054\uffde\055\uffde\056\uffde\057\uffde\072\uffde\001\002\000" +
    "\004\033\uffc1\001\002\000\026\004\uffd9\024\uffd9\026\uffd9" +
    "\027\uffd9\033\uffd9\034\uffd9\035\uffd9\063\uffd9\064\uffd9\072" +
    "\uffd9\001\002\000\020\024\uffd5\026\uffd5\027\uffd5\033\uffd5" +
    "\034\uffd5\035\uffd5\072\uffd5\001\002\000\026\004\uffdb\024" +
    "\uffdb\026\uffdb\027\uffdb\033\uffdb\034\uffdb\035\uffdb\063\uffdb" +
    "\064\uffdb\072\uffdb\001\002\000\026\004\uffd8\024\uffd8\026" +
    "\uffd8\027\uffd8\033\uffd8\034\uffd8\035\uffd8\063\uffd8\064\uffd8" +
    "\072\uffd8\001\002\000\026\004\uffc0\024\uffc0\026\uffc0\027" +
    "\uffc0\033\uffc0\034\uffc0\035\uffc0\041\uffc0\042\uffc0\072\uffc0" +
    "\001\002\000\004\033\122\001\002\000\026\004\uffda\024" +
    "\uffda\026\uffda\027\uffda\033\uffda\034\uffda\035\uffda\063\uffda" +
    "\064\uffda\072\uffda\001\002\000\072\002\ufff6\005\ufff6\006" +
    "\ufff6\007\ufff6\010\ufff6\011\ufff6\013\ufff6\014\ufff6\015\ufff6" +
    "\016\ufff6\020\ufff6\021\ufff6\022\ufff6\023\ufff6\046\ufff6\047" +
    "\ufff6\052\ufff6\054\ufff6\060\ufff6\061\ufff6\066\ufff6\067\ufff6" +
    "\071\ufff6\072\ufff6\073\ufff6\074\ufff6\075\ufff6\077\ufff6\001" +
    "\002\000\024\024\uffd4\026\uffd4\027\uffd4\033\uffd4\034\uffd4" +
    "\035\uffd4\041\120\042\116\072\uffd4\001\002\000\006\033" +
    "\uffbb\035\uffbb\001\002\000\006\033\uffc2\035\104\001\002" +
    "\000\006\033\uffbc\035\uffbc\001\002\000\026\004\uffbf\024" +
    "\uffbf\026\uffbf\027\uffbf\033\uffbf\034\uffbf\035\uffbf\041\uffbf" +
    "\042\uffbf\072\uffbf\001\002\000\006\037\123\040\124\001" +
    "\002\000\020\060\033\061\040\071\023\073\031\074\010" +
    "\075\057\077\051\001\002\000\020\060\033\061\040\071" +
    "\023\073\031\074\010\075\057\077\051\001\002\000\026" +
    "\004\uffbd\024\uffbd\026\uffbd\027\uffbd\033\uffbd\034\uffbd\035" +
    "\uffbd\041\uffbd\042\uffbd\072\uffbd\001\002\000\026\004\uffbe" +
    "\024\uffbe\026\uffbe\027\uffbe\033\uffbe\034\uffbe\035\uffbe\041" +
    "\uffbe\042\uffbe\072\uffbe\001\002\000\024\024\uffcf\026\uffcf" +
    "\027\uffcf\033\uffcf\034\uffcf\035\uffcf\063\uffcf\064\uffcf\072" +
    "\uffcf\001\002\000\034\012\uffe1\037\uffe1\041\074\042\uffe1" +
    "\044\uffe1\045\uffe1\047\uffe1\053\uffe1\054\uffe1\055\uffe1\056" +
    "\071\057\072\072\uffe1\001\002\000\030\046\uffb2\047\uffb2" +
    "\052\uffb2\054\uffb2\060\uffb2\061\uffb2\071\uffb2\073\uffb2\074" +
    "\uffb2\075\uffb2\077\uffb2\001\002\000\030\046\uffb3\047\uffb3" +
    "\052\uffb3\054\uffb3\060\uffb3\061\uffb3\071\uffb3\073\uffb3\074" +
    "\uffb3\075\uffb3\077\uffb3\001\002\000\030\046\064\047\066" +
    "\052\030\054\053\060\033\061\040\071\023\073\031\074" +
    "\010\075\057\077\051\001\002\000\072\002\ufff1\005\ufff1" +
    "\006\ufff1\007\ufff1\010\ufff1\011\ufff1\013\ufff1\014\ufff1\015" +
    "\ufff1\016\ufff1\020\ufff1\021\ufff1\022\ufff1\023\ufff1\046\ufff1" +
    "\047\ufff1\052\ufff1\054\ufff1\060\ufff1\061\ufff1\066\ufff1\067" +
    "\ufff1\071\ufff1\072\ufff1\073\ufff1\074\ufff1\075\ufff1\077\ufff1" +
    "\001\002\000\012\012\uffae\044\uffae\045\uffae\072\uffae\001" +
    "\002\000\030\012\uffad\037\137\041\074\042\067\044\uffad" +
    "\045\uffad\054\070\055\073\056\071\057\072\072\uffad\001" +
    "\002\000\030\046\064\047\066\052\030\054\053\060\033" +
    "\061\040\071\023\073\031\074\010\075\057\077\051\001" +
    "\002\000\026\012\uffb1\041\074\042\067\044\uffb1\045\uffb1" +
    "\054\070\055\073\056\071\057\072\072\uffb1\001\002\000" +
    "\072\002\ufff4\005\ufff4\006\ufff4\007\ufff4\010\ufff4\011\ufff4" +
    "\013\ufff4\014\ufff4\015\ufff4\016\ufff4\020\ufff4\021\ufff4\022" +
    "\ufff4\023\ufff4\046\ufff4\047\ufff4\052\ufff4\054\ufff4\060\ufff4" +
    "\061\ufff4\066\ufff4\067\ufff4\071\ufff4\072\ufff4\073\ufff4\074" +
    "\ufff4\075\ufff4\077\ufff4\001\002\000\020\041\074\042\067" +
    "\054\070\055\073\056\071\057\072\072\143\001\002\000" +
    "\072\002\ufff2\005\ufff2\006\ufff2\007\ufff2\010\ufff2\011\ufff2" +
    "\013\ufff2\014\ufff2\015\ufff2\016\ufff2\020\ufff2\021\ufff2\022" +
    "\ufff2\023\ufff2\046\ufff2\047\ufff2\052\ufff2\054\ufff2\060\ufff2" +
    "\061\ufff2\066\ufff2\067\ufff2\071\ufff2\072\ufff2\073\ufff2\074" +
    "\ufff2\075\ufff2\077\ufff2\001\002\000\020\024\uffd7\026\uffd7" +
    "\027\uffd7\033\uffd7\034\uffd7\035\uffd7\072\uffd7\001\002\000" +
    "\024\024\uffd6\026\uffd6\027\uffd6\033\uffd6\034\uffd6\035\uffd6" +
    "\041\120\042\116\072\uffd6\001\002\000\004\072\ufffc\001" +
    "\002\000\072\002\ufff8\005\ufff8\006\ufff8\007\ufff8\010\ufff8" +
    "\011\ufff8\013\ufff8\014\ufff8\015\ufff8\016\ufff8\020\ufff8\021" +
    "\ufff8\022\ufff8\023\ufff8\046\ufff8\047\ufff8\052\ufff8\054\ufff8" +
    "\060\ufff8\061\ufff8\066\ufff8\067\ufff8\071\ufff8\072\ufff8\073" +
    "\ufff8\074\ufff8\075\ufff8\077\ufff8\001\002\000\006\047\uffe8" +
    "\072\uffe8\001\002\000\072\002\ufff9\005\ufff9\006\ufff9\007" +
    "\ufff9\010\ufff9\011\ufff9\013\ufff9\014\ufff9\015\ufff9\016\ufff9" +
    "\020\ufff9\021\ufff9\022\ufff9\023\ufff9\046\ufff9\047\ufff9\052" +
    "\ufff9\054\ufff9\060\ufff9\061\ufff9\066\ufff9\067\ufff9\071\ufff9" +
    "\072\ufff9\073\ufff9\074\ufff9\075\ufff9\077\ufff9\001\002\000" +
    "\020\041\074\042\067\053\153\054\070\055\073\056\071" +
    "\057\072\001\002\000\034\012\uffdf\037\uffdf\041\uffdf\042" +
    "\uffdf\044\uffdf\045\uffdf\047\uffdf\053\uffdf\054\uffdf\055\uffdf" +
    "\056\uffdf\057\uffdf\072\uffdf\001\002\000\064\005\026\006" +
    "\006\007\052\010\005\011\007\015\012\016\156\020\054" +
    "\021\056\022\022\023\042\046\017\047\020\052\030\054" +
    "\053\060\033\061\040\066\035\067\004\071\023\072\036" +
    "\073\031\074\010\075\057\077\051\001\002\000\010\011" +
    "\uffa1\015\uffa1\072\uffa1\001\002\000\006\054\160\055\162" +
    "\001\002\000\072\002\ufffa\005\ufffa\006\ufffa\007\ufffa\010" +
    "\ufffa\011\ufffa\013\ufffa\014\ufffa\015\ufffa\016\ufffa\020\ufffa" +
    "\021\ufffa\022\ufffa\023\ufffa\046\ufffa\047\ufffa\052\ufffa\054" +
    "\ufffa\060\ufffa\061\ufffa\066\ufffa\067\ufffa\071\ufffa\072\ufffa" +
    "\073\ufffa\074\ufffa\075\ufffa\077\ufffa\001\002\000\012\025" +
    "\uffa3\047\uffa3\073\uffa3\074\uffa3\001\002\000\012\025\163" +
    "\047\167\073\166\074\165\001\002\000\012\025\uffa4\047" +
    "\uffa4\073\uffa4\074\uffa4\001\002\000\022\011\uffa6\015\uffa6" +
    "\017\uffa6\025\uffa6\047\uffa6\072\uffa6\073\uffa6\074\uffa6\001" +
    "\002\000\010\011\uffa2\015\uffa2\072\uffa2\001\002\000\022" +
    "\011\uffa7\015\uffa7\017\uffa7\025\uffa7\047\uffa7\072\uffa7\073" +
    "\uffa7\074\uffa7\001\002\000\022\011\uffa8\015\uffa8\017\uffa8" +
    "\025\uffa8\047\uffa8\072\uffa8\073\uffa8\074\uffa8\001\002\000" +
    "\022\011\uffa9\015\uffa9\017\uffa9\025\uffa9\047\uffa9\072\uffa9" +
    "\073\uffa9\074\uffa9\001\002\000\022\004\uffcb\024\uffcb\026" +
    "\uffcb\027\uffcb\033\uffcb\034\uffcb\035\uffcb\072\uffcb\001\002" +
    "\000\026\004\uffca\024\uffca\026\uffca\027\uffca\033\uffca\034" +
    "\uffca\035\uffca\041\120\042\116\072\uffca\001\002\000\072" +
    "\002\ufff3\005\ufff3\006\ufff3\007\ufff3\010\ufff3\011\ufff3\013" +
    "\ufff3\014\ufff3\015\ufff3\016\ufff3\020\ufff3\021\ufff3\022\ufff3" +
    "\023\ufff3\046\ufff3\047\ufff3\052\ufff3\054\ufff3\060\ufff3\061" +
    "\ufff3\066\ufff3\067\ufff3\071\ufff3\072\ufff3\073\ufff3\074\ufff3" +
    "\075\ufff3\077\ufff3\001\002\000\010\011\uffaa\015\uffaa\072" +
    "\uffaa\001\002\000\004\072\175\001\002\000\062\005\026" +
    "\006\006\007\052\010\005\011\007\015\012\020\054\021" +
    "\056\022\022\023\042\046\017\047\020\052\030\054\053" +
    "\060\033\061\040\066\035\067\004\071\023\072\036\073" +
    "\031\074\010\075\057\077\051\001\002\000\064\005\026" +
    "\006\006\007\052\010\005\011\007\014\177\015\012\020" +
    "\054\021\056\022\022\023\042\046\017\047\020\052\030" +
    "\054\053\060\033\061\040\066\035\067\004\071\023\072" +
    "\036\073\031\074\010\075\057\077\051\001\002\000\010" +
    "\011\uffab\015\uffab\072\uffab\001\002\000\012\012\uffaf\044" +
    "\uffaf\045\uffaf\072\uffaf\001\002\000\020\037\uffde\041\uffde" +
    "\042\uffde\054\uffde\055\uffde\056\uffde\057\uffde\001\002\000" +
    "\022\004\uffc9\024\uffc9\026\uffc9\027\uffc9\033\uffc9\034\uffc9" +
    "\035\uffc9\072\uffc9\001\002\000\072\002\ufff5\005\ufff5\006" +
    "\ufff5\007\ufff5\010\ufff5\011\ufff5\013\ufff5\014\ufff5\015\ufff5" +
    "\016\ufff5\020\ufff5\021\ufff5\022\ufff5\023\ufff5\046\ufff5\047" +
    "\ufff5\052\ufff5\054\ufff5\060\ufff5\061\ufff5\066\ufff5\067\ufff5" +
    "\071\ufff5\072\ufff5\073\ufff5\074\ufff5\075\ufff5\077\ufff5\001" +
    "\002\000\014\006\006\007\052\010\005\020\054\022\022" +
    "\001\002\000\026\004\uffc8\024\uffc8\026\uffc8\027\uffc8\033" +
    "\uffc8\034\uffc8\035\uffc8\041\120\042\116\072\uffc8\001\002" +
    "\000\006\063\uffc6\064\uffc6\001\002\000\006\063\212\064" +
    "\211\001\002\000\006\063\uffc5\064\uffc5\001\002\000\016" +
    "\024\105\026\113\027\107\034\110\063\uffc3\064\uffc3\001" +
    "\002\000\022\004\uffc7\024\uffc7\026\uffc7\027\uffc7\033\uffc7" +
    "\034\uffc7\035\uffc7\072\uffc7\001\002\000\006\063\uffc4\064" +
    "\uffc4\001\002\000\004\002\001\001\002\000\010\011\uffec" +
    "\015\uffec\072\uffec\001\002\000\010\011\uffed\015\uffed\072" +
    "\uffed\001\002\000\072\002\ufff7\005\ufff7\006\ufff7\007\ufff7" +
    "\010\ufff7\011\ufff7\013\ufff7\014\ufff7\015\ufff7\016\ufff7\020" +
    "\ufff7\021\ufff7\022\ufff7\023\ufff7\046\ufff7\047\ufff7\052\ufff7" +
    "\054\ufff7\060\ufff7\061\ufff7\066\ufff7\067\ufff7\071\ufff7\072" +
    "\ufff7\073\ufff7\074\ufff7\075\ufff7\077\ufff7\001\002\000\012" +
    "\025\163\047\167\073\166\074\165\001\002\000\012\025" +
    "\163\047\167\073\166\074\165\001\002\000\004\017\223" +
    "\001\002\000\004\072\224\001\002\000\062\005\uffa5\006" +
    "\uffa5\007\uffa5\010\uffa5\011\uffa5\015\uffa5\020\uffa5\021\uffa5" +
    "\022\uffa5\023\uffa5\046\uffa5\047\uffa5\052\uffa5\054\uffa5\060" +
    "\uffa5\061\uffa5\066\uffa5\067\uffa5\071\uffa5\072\uffa5\073\uffa5" +
    "\074\uffa5\075\uffa5\077\uffa5\001\002\000\010\012\226\044" +
    "\131\045\132\001\002\000\004\072\227\001\002\000\062" +
    "\005\026\006\006\007\052\010\005\011\007\015\012\020" +
    "\054\021\056\022\022\023\042\046\017\047\020\052\030" +
    "\054\053\060\033\061\040\066\035\067\004\071\023\072" +
    "\036\073\031\074\010\075\057\077\051\001\002\000\066" +
    "\005\026\006\006\007\052\010\005\011\007\013\uffac\014" +
    "\uffac\015\012\020\054\021\056\022\022\023\042\046\017" +
    "\047\020\052\030\054\053\060\033\061\040\066\035\067" +
    "\004\071\023\072\036\073\031\074\010\075\057\077\051" +
    "\001\002\000\024\024\uffd1\026\uffd1\027\uffd1\033\uffd1\034" +
    "\uffd1\035\uffd1\063\uffd1\064\uffd1\072\uffd1\001\002\000\004" +
    "\072\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\230\000\054\003\013\004\057\005\054\006\031\007" +
    "\012\010\033\011\015\014\020\020\014\025\040\026\024" +
    "\030\043\031\026\034\036\036\046\037\042\040\023\042" +
    "\045\043\044\045\010\046\047\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\025\040\026" +
    "\024\030\043\042\224\043\044\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\027\217\001\001\000\012\014" +
    "\020\031\026\045\215\046\214\001\001\000\002\001\001" +
    "\000\012\015\111\022\204\023\110\035\201\001\001\000" +
    "\050\004\156\005\054\006\031\007\012\010\033\014\020" +
    "\020\014\025\040\026\024\030\043\031\026\034\036\036" +
    "\046\037\042\040\023\042\045\043\044\045\010\046\047" +
    "\001\001\000\012\025\040\026\200\030\043\043\177\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\015\111\022\170\023\110\035\167\001\001\000\052" +
    "\004\057\005\054\006\031\007\012\010\033\011\153\014" +
    "\020\020\014\025\040\026\024\030\043\031\026\034\036" +
    "\036\046\037\042\040\023\042\045\043\044\045\010\046" +
    "\047\001\001\000\010\025\040\026\151\030\043\001\001" +
    "\000\002\001\001\000\004\010\147\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\015\111\022\144\023\110\035\143\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\025\040\026\141" +
    "\030\043\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\017\132\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\025\040\026\127\030\043\001\001\000\002\001\001" +
    "\000\012\015\111\022\114\023\110\035\105\001\001\000" +
    "\004\010\060\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\025\040\026" +
    "\064\030\043\001\001\000\010\025\040\026\102\030\043" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\025" +
    "\040\026\101\030\043\001\001\000\010\025\040\026\100" +
    "\030\043\001\001\000\010\025\040\026\077\030\043\001" +
    "\001\000\010\025\040\026\076\030\043\001\001\000\010" +
    "\025\040\026\075\030\043\001\001\000\010\025\040\026" +
    "\074\030\043\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\041\116\001\001\000\002\001" +
    "\001\000\006\015\111\023\120\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\025\125\001" +
    "\001\000\004\025\124\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\025\040\026\135\030\043" +
    "\043\134\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\025\040\026\137\030\043\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\041\116\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\052" +
    "\004\156\005\054\006\031\007\012\010\033\014\020\020" +
    "\014\025\040\026\024\030\043\031\026\034\036\036\046" +
    "\037\042\040\023\042\045\043\044\044\154\045\010\046" +
    "\047\001\001\000\002\001\001\000\004\033\160\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\027\163\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\041\116\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\052\004\057\005" +
    "\054\006\031\007\012\010\033\011\175\014\020\020\014" +
    "\025\040\026\024\030\043\031\026\034\036\036\046\037" +
    "\042\040\023\042\045\043\044\045\010\046\047\001\001" +
    "\000\050\004\156\005\054\006\031\007\012\010\033\014" +
    "\020\020\014\025\040\026\024\030\043\031\026\034\036" +
    "\036\046\037\042\040\023\042\045\043\044\045\010\046" +
    "\047\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\021" +
    "\206\034\205\036\207\001\001\000\004\041\116\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\035\212\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\027\220\001\001\000\004\027\221" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\017\132\001\001\000\002\001\001\000\052" +
    "\004\057\005\054\006\031\007\012\010\033\011\227\014" +
    "\020\020\014\025\040\026\024\030\043\031\026\034\036" +
    "\036\046\037\042\040\023\042\045\043\044\045\010\046" +
    "\047\001\001\000\050\004\156\005\054\006\031\007\012" +
    "\010\033\014\020\020\014\025\040\026\024\030\043\031" +
    "\026\034\036\036\046\037\042\040\023\042\045\043\044" +
    "\045\010\046\047\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

	vm = new VarManager();


 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }


public VarManager vm;

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // for_stmt ::= for_head i_stmt for_tail 
            { parser.Tree.reduce(3,"for_stmt",0);
              Object[] RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		myVar[] x = (myVar[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String[] y = (String[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
			System.out.println("for cycle");
			RESULT= new Object[5];
			RESULT[0] = (myVar)x[0];
			RESULT[1] = (myVar)x[1];
			RESULT[2] = (myVar)x[2];			
			RESULT[3] = parser.vm.extractVar(y[1].toString());  
			RESULT[4] = (String)y[0];					
              CUP$parser$result = new java_cup.runtime.Symbol(35/*for_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // for_tail ::= Com_For_e i_Op_ps for_arg 
            { parser.Tree.reduce(3,"for_tail",0);
              String[] RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 	//passiamo un vettore di 2 elementi stringe contenenti l'operatore e il fattore
			System.out.println("dentro for tail");
			RESULT= new String[2];
			RESULT[0]= (String)x.toString();
			RESULT[1]= ((myVar)y).getName();
			System.out.println(" valore: "+y.toString());
			System.out.println("operatore: "+x.toString()); 		
              CUP$parser$result = new java_cup.runtime.Symbol(34/*for_tail*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // i_Op_ps ::= Minus 
            { parser.Tree.reduce(1,"i_Op_ps",0);
              String RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = x; 						
              CUP$parser$result = new java_cup.runtime.Symbol(25/*i_Op_ps*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // i_Op_ps ::= Plus 
            { parser.Tree.reduce(1,"i_Op_ps",0);
              String RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = x; 						
              CUP$parser$result = new java_cup.runtime.Symbol(25/*i_Op_ps*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // for_head ::= Com_For for_arg for_arg for_arg Com_For_m EL 
            { parser.Tree.reduce(6,"for_head",0);
              myVar[] RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int zleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int zright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		myVar z = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 System.out.println("for_head variabili \n"+x.toString()+"\n"+y.toString()+"\n"+z.toString());
		// passiamo un vettore contenente le tre variabili sulle quali controllare il ciclo for
			RESULT= new myVar[3];
			RESULT[0]= x;
			RESULT[1]= y;
			RESULT[2]= z;							
              CUP$parser$result = new java_cup.runtime.Symbol(23/*for_head*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // for_arg ::= ID 
            { parser.Tree.reduce(1,"for_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT= new myVar(myVar._string, x); 
              CUP$parser$result = new java_cup.runtime.Symbol(21/*for_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // for_arg ::= Vint 
            { parser.Tree.reduce(1,"for_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Float x = (Float)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT= new myVar(myVar._float, x.floatValue()); 	
              CUP$parser$result = new java_cup.runtime.Symbol(21/*for_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // for_arg ::= Int 
            { parser.Tree.reduce(1,"for_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Integer x = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new myVar(myVar._int, x.intValue()); 	
              CUP$parser$result = new java_cup.runtime.Symbol(21/*for_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // for_arg ::= Var 
            { parser.Tree.reduce(1,"for_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new myVar(x); 				
              CUP$parser$result = new java_cup.runtime.Symbol(21/*for_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // if_stmt ::= if_head Com_If_e 
            { parser.Tree.reduce(2,"if_stmt",0);
              Object[] RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(36/*if_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // if_stmt ::= if_head Com_If_m EL i_stmt Com_If_e 
            { parser.Tree.reduce(5,"if_stmt",0);
              Object[] RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(36/*if_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // if_head ::= Com_If conf_exp Com_If_2 EL i_stmt 
            { parser.Tree.reduce(5,"if_head",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(10/*if_head*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // conf_exp ::= conf_exp cond_if arit_stmt 
            { parser.Tree.reduce(3,"conf_exp",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(32/*conf_exp*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // conf_exp ::= conf_exp cond_if conf 
            { parser.Tree.reduce(3,"conf_exp",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(32/*conf_exp*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // conf_exp ::= C_Not conf 
            { parser.Tree.reduce(2,"conf_exp",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(32/*conf_exp*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // conf_exp ::= conf 
            { parser.Tree.reduce(1,"conf_exp",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(32/*conf_exp*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // conf ::= arit_stmt Cond arit_stmt 
            { parser.Tree.reduce(3,"conf",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(33/*conf*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // cond_if ::= C_Andd 
            { parser.Tree.reduce(1,"cond_if",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*cond_if*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // cond_if ::= C_Orr 
            { parser.Tree.reduce(1,"cond_if",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(13/*cond_if*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // i_arg ::= Bool 
            { parser.Tree.reduce(1,"i_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Boolean x = (Boolean)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT= new myVar(myVar._bool, new Boolean(x)); 		
              CUP$parser$result = new java_cup.runtime.Symbol(19/*i_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // i_arg ::= FUnit 
            { parser.Tree.reduce(1,"i_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT= new myVar(myVar._string, x); 			
              CUP$parser$result = new java_cup.runtime.Symbol(19/*i_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // i_arg ::= IUnit 
            { parser.Tree.reduce(1,"i_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT= new myVar(myVar._string, x); 			
              CUP$parser$result = new java_cup.runtime.Symbol(19/*i_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // i_arg ::= Str 
            { parser.Tree.reduce(1,"i_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 System.out.println("str: "+x); 
					RESULT= new myVar(myVar._string, x); 			
              CUP$parser$result = new java_cup.runtime.Symbol(19/*i_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // i_arg ::= Vint 
            { parser.Tree.reduce(1,"i_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Float x = (Float)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT= new myVar(myVar._float, x.floatValue()); 		
              CUP$parser$result = new java_cup.runtime.Symbol(19/*i_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // i_arg ::= Int 
            { parser.Tree.reduce(1,"i_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Integer x = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new myVar(myVar._int, x.intValue()); 		
              CUP$parser$result = new java_cup.runtime.Symbol(19/*i_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // i_arg ::= GMA 
            { parser.Tree.reduce(1,"i_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Calendar x = (Calendar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new myVar(myVar._string, x);			
              CUP$parser$result = new java_cup.runtime.Symbol(19/*i_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // bool_op ::= C_Or 
            { parser.Tree.reduce(1,"bool_op",0);
              String RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT =x; 
              CUP$parser$result = new java_cup.runtime.Symbol(31/*bool_op*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // bool_op ::= C_And 
            { parser.Tree.reduce(1,"bool_op",0);
              String RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT =x; 
              CUP$parser$result = new java_cup.runtime.Symbol(31/*bool_op*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // cc_conds ::= _where Criteria C_Ug i_arg 
            { parser.Tree.reduce(4,"cc_conds",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*cc_conds*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // cc_conds ::= _where Criteria Cond i_arg 
            { parser.Tree.reduce(4,"cc_conds",0);
              Object RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = new java_cup.runtime.Symbol(17/*cc_conds*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // i_cc_conds ::= i_cc_conds bool_op cc_conds 
            { parser.Tree.reduce(3,"i_cc_conds",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*i_cc_conds*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // i_cc_conds ::= cc_conds 
            { parser.Tree.reduce(1,"i_cc_conds",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(16/*i_cc_conds*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // _where ::= Where 
            { parser.Tree.reduce(1,"_where",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*_where*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // _where ::= 
            { parser.Tree.reduce(0,"_where",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(11/*_where*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // comm_find_2 ::= comm_find_2 Name 
            { parser.Tree.reduce(2,"comm_find_2",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*comm_find_2*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // comm_find_2 ::= comm_find_2 Name param 
            { parser.Tree.reduce(3,"comm_find_2",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*comm_find_2*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // comm_find_2 ::= commands_oa 
            { parser.Tree.reduce(1,"comm_find_2",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*comm_find_2*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // comm_find_2 ::= commands 
            { parser.Tree.reduce(1,"comm_find_2",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(15/*comm_find_2*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // comm_find ::= comm_find Com_Ex comm_find_2 Pv 
            { parser.Tree.reduce(4,"comm_find",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*comm_find*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // comm_find ::= comm_find i_cc_conds 
            { parser.Tree.reduce(2,"comm_find",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*comm_find*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // comm_find ::= comm_find param 
            { parser.Tree.reduce(2,"comm_find",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*comm_find*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // comm_find ::= Com_Find i_cc_conds 
            { parser.Tree.reduce(2,"comm_find",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*comm_find*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // comm_find ::= Com_Find param 
            { parser.Tree.reduce(2,"comm_find",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(14/*comm_find*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // commands ::= Com_Cp 
            { parser.Tree.reduce(1,"commands",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(26/*commands*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // commands ::= Com_Rm 
            { parser.Tree.reduce(1,"commands",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(26/*commands*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // commands ::= Com_Mov 
            { parser.Tree.reduce(1,"commands",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(26/*commands*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // commands_oa ::= Com_Ls Order 
            { parser.Tree.reduce(2,"commands_oa",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*commands_oa*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // commands_oa ::= Com_Ls 
            { parser.Tree.reduce(1,"commands_oa",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*commands_oa*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // commands_oa ::= Com_Cd Minor 
            { parser.Tree.reduce(2,"commands_oa",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*commands_oa*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // commands_oa ::= Com_Cd 
            { parser.Tree.reduce(1,"commands_oa",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(28/*commands_oa*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sh_stmt ::= commands_oa 
            { parser.Tree.reduce(1,"sh_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*sh_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sh_stmt ::= sh_stmt i_cc_conds 
            { parser.Tree.reduce(2,"sh_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*sh_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sh_stmt ::= sh_stmt param 
            { parser.Tree.reduce(2,"sh_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*sh_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sh_stmt ::= commands i_cc_conds 
            { parser.Tree.reduce(2,"sh_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*sh_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // sh_stmt ::= commands param 
            { parser.Tree.reduce(2,"sh_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(3/*sh_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // param ::= Obj 
            { parser.Tree.reduce(1,"param",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(27/*param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // param ::= Ext 
            { parser.Tree.reduce(1,"param",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(27/*param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // param ::= File 
            { parser.Tree.reduce(1,"param",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(27/*param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // param ::= Path 
            { parser.Tree.reduce(1,"param",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(27/*param*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // arit_arg ::= i_arg 
            { parser.Tree.reduce(1,"arit_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = ((myVar)x); System.out.println("i_arg"); 
              CUP$parser$result = new java_cup.runtime.Symbol(22/*arit_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // arit_arg ::= Var 
            { parser.Tree.reduce(1,"arit_arg",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = parser.vm.extractVar(x); 
							System.out.println("Var: "+x); 
              CUP$parser$result = new java_cup.runtime.Symbol(22/*arit_arg*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // arit_stmt ::= C_Not arit_stmt 
            { parser.Tree.reduce(2,"arit_stmt",0);
              myVar RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = parser.vm.makeSOper(((myVar)x),s); 
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // arit_stmt ::= RO arit_stmt RC 
            { parser.Tree.reduce(3,"arit_stmt",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = ((myVar)x); 		
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // arit_stmt ::= arit_arg 
            { parser.Tree.reduce(1,"arit_stmt",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = ((myVar)x); 		
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // arit_stmt ::= Minus arit_stmt 
            { parser.Tree.reduce(2,"arit_stmt",0);
              myVar RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = parser.vm.makeSOper(((myVar)x),s); 
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // arit_stmt ::= arit_stmt C_Or arit_stmt 
            { parser.Tree.reduce(3,"arit_stmt",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
			System.out.println(s);
			((myVar)x).printVar(); 
			System.out.println("segno operazione: "+s); y.printVar(); 
			RESULT = parser.vm.makeOper(((myVar)x),((myVar)y),s); 		
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // arit_stmt ::= arit_stmt C_And arit_stmt 
            { parser.Tree.reduce(3,"arit_stmt",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
			System.out.println(s);
			((myVar)x).printVar(); 
			System.out.println("segno operazione: "+s); y.printVar(); 
			RESULT = parser.vm.makeOper(((myVar)x),((myVar)y),s); 		
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // arit_stmt ::= arit_stmt Minus arit_stmt 
            { parser.Tree.reduce(3,"arit_stmt",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
			System.out.println(s);
			((myVar)x).printVar(); 
			System.out.println("segno operazione: "+s); y.printVar(); 
			RESULT = parser.vm.makeOper(((myVar)x),((myVar)y),s); 		
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // arit_stmt ::= arit_stmt Plus arit_stmt 
            { parser.Tree.reduce(3,"arit_stmt",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
			System.out.println(s);
			((myVar)x).printVar(); 
			System.out.println("segno operazione: "+s); y.printVar(); 
			RESULT = parser.vm.makeOper(((myVar)x),((myVar)y),s); 		
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // arit_stmt ::= arit_stmt Div arit_stmt 
            { parser.Tree.reduce(3,"arit_stmt",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
			System.out.println(s);
			((myVar)x).printVar(); 
			System.out.println("segno operazione: "+s); y.printVar(); 
			RESULT = parser.vm.makeOper(((myVar)x),((myVar)y),s); 		
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // arit_stmt ::= arit_stmt Times arit_stmt 
            { parser.Tree.reduce(3,"arit_stmt",0);
              myVar RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		myVar x = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
			System.out.println(s);
			((myVar)x).printVar(); 
			System.out.println("segno operazione: "+s); y.printVar(); 
			RESULT = parser.vm.makeOper(((myVar)x),((myVar)y),s); 		
              CUP$parser$result = new java_cup.runtime.Symbol(20/*arit_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // init_stmt ::= init_stmt assig_stmt 
            { parser.Tree.reduce(2,"init_stmt",0);
              Object RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Object x = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 parser.vm.add_var(((myVar)x)); 	
              CUP$parser$result = new java_cup.runtime.Symbol(4/*init_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // init_stmt ::= Com_Str assig_stmt 
            { parser.Tree.reduce(2,"init_stmt",0);
              Object RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		Object x = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 parser.vm.add_var(((myVar)x)); 	
              CUP$parser$result = new java_cup.runtime.Symbol(4/*init_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // assig_stmt ::= Var 
            { parser.Tree.reduce(1,"assig_stmt",0);
              Object RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 RESULT = new myVar(x); 		
              CUP$parser$result = new java_cup.runtime.Symbol(6/*assig_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // assig_stmt ::= Var C_Ug arit_stmt 
            { parser.Tree.reduce(3,"assig_stmt",0);
              Object RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right;
		myVar y = (myVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-0)).value;
		 ((myVar)y).setName(x); RESULT = y; 	
              CUP$parser$result = new java_cup.runtime.Symbol(6/*assig_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // str_stmt ::= str_stmt if_stmt 
            { parser.Tree.reduce(2,"str_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*str_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // str_stmt ::= str_stmt for_stmt 
            { parser.Tree.reduce(2,"str_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*str_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // str_stmt ::= for_stmt 
            { parser.Tree.reduce(1,"str_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*str_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // str_stmt ::= if_stmt 
            { parser.Tree.reduce(1,"str_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(5/*str_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // stmt ::= EL 
            { parser.Tree.reduce(1,"stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // stmt ::= conf_exp EL 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt ::= Com_P arit_stmt EL 
            { parser.Tree.reduce(3,"stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt ::= throw_s EL 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt ::= start_s EL 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= comm_find EL 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= sh_stmt EL 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= str_stmt EL 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= assig_stmt EL 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT = null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object x = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 parser.vm.assig(((myVar)x)); 
              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= init_stmt EL 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT = null;
		 parser.vm.getListVar(); 	
              CUP$parser$result = new java_cup.runtime.Symbol(2/*stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // i_stmt ::= i_stmt stmt 
            { parser.Tree.reduce(2,"i_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*i_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // i_stmt ::= stmt 
            { parser.Tree.reduce(1,"i_stmt",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(7/*i_stmt*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // throw_s ::= Throw_S File 
            { parser.Tree.reduce(2,"throw_s",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(30/*throw_s*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // start_s ::= Start_S File 
            { parser.Tree.reduce(2,"start_s",0);
              String RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(29/*start_s*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // script ::= start_s i_stmt End_S 
            { parser.Tree.reduce(3,"script",0);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(18/*script*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // S ::= i_stmt 
            { parser.Tree.reduce(1,"S",1);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*S*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= 
            { parser.Tree.reduce(0,"S",1);
              Object RESULT = null;

              CUP$parser$result = new java_cup.runtime.Symbol(1/*S*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            { 
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

