
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Aug 17 12:02:12 CEST 2011
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Start_S = 53;
  public static final int Com_Cd = 6;
  public static final int Uminus = 60;
  public static final int Com_Rm = 4;
  public static final int Vint = 58;
  public static final int Com_If = 7;
  public static final int SO = 38;
  public static final int Com_For = 11;
  public static final int C_Orr = 35;
  public static final int C_Ugg = 33;
  public static final int Com_Ex = 2;
  public static final int Name = 50;
  public static final int Var = 37;
  public static final int C_Not = 36;
  public static final int C_And = 31;
  public static final int Day = 24;
  public static final int SC = 39;
  public static final int Com_Mov = 16;
  public static final int File = 20;
  public static final int Times = 44;
  public static final int Str = 55;
  public static final int Com_Find = 3;
  public static final int Com_If_2 = 8;
  public static final int RO = 40;
  public static final int Int = 57;
  public static final int Order = 22;
  public static final int ID = 19;
  public static final int EOF = 0;
  public static final int FUnit = 46;
  public static final int C_Or = 32;
  public static final int RC = 41;
  public static final int error = 1;
  public static final int Throw_S = 52;
  public static final int Com_For_m = 13;
  public static final int Div = 45;
  public static final int Ext = 18;
  public static final int Pv = 49;
  public static final int Path = 21;
  public static final int EL = 56;
  public static final int C_Ug = 30;
  public static final int IUnit = 47;
  public static final int Com_For_e = 12;
  public static final int Cond = 29;
  public static final int Obj = 26;
  public static final int Com_P = 17;
  public static final int Com_If_m = 9;
  public static final int Month = 23;
  public static final int End_S = 54;
  public static final int C_Andd = 34;
  public static final int Com_If_e = 10;
  public static final int Minor = 48;
  public static final int Bool = 61;
  public static final int Result = 51;
  public static final int Com_Cp = 5;
  public static final int Minus = 42;
  public static final int Com_Ls = 14;
  public static final int Where = 27;
  public static final int Criteria = 25;
  public static final int Plus = 43;
  public static final int GMA = 59;
  public static final int Com_Str = 15;
  public static final int Prep_supp = 28;
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[53]=new String("Start_S");
		TT[6]=new String("Com_Cd");
		TT[60]=new String("Uminus");
		TT[4]=new String("Com_Rm");
		TT[58]=new String("Vint");
		TT[7]=new String("Com_If");
		TT[38]=new String("SO");
		TT[11]=new String("Com_For");
		TT[35]=new String("C_Orr");
		TT[33]=new String("C_Ugg");
		TT[2]=new String("Com_Ex");
		TT[50]=new String("Name");
		TT[37]=new String("Var");
		TT[36]=new String("C_Not");
		TT[31]=new String("C_And");
		TT[24]=new String("Day");
		TT[39]=new String("SC");
		TT[16]=new String("Com_Mov");
		TT[20]=new String("File");
		TT[44]=new String("Times");
		TT[55]=new String("Str");
		TT[3]=new String("Com_Find");
		TT[8]=new String("Com_If_2");
		TT[40]=new String("RO");
		TT[57]=new String("Int");
		TT[22]=new String("Order");
		TT[19]=new String("ID");
		TT[0]=new String("EOF");
		TT[46]=new String("FUnit");
		TT[32]=new String("C_Or");
		TT[41]=new String("RC");
		TT[1]=new String("error");
		TT[52]=new String("Throw_S");
		TT[13]=new String("Com_For_m");
		TT[45]=new String("Div");
		TT[18]=new String("Ext");
		TT[49]=new String("Pv");
		TT[21]=new String("Path");
		TT[56]=new String("EL");
		TT[30]=new String("C_Ug");
		TT[47]=new String("IUnit");
		TT[12]=new String("Com_For_e");
		TT[29]=new String("Cond");
		TT[26]=new String("Obj");
		TT[17]=new String("Com_P");
		TT[9]=new String("Com_If_m");
		TT[23]=new String("Month");
		TT[54]=new String("End_S");
		TT[34]=new String("C_Andd");
		TT[10]=new String("Com_If_e");
		TT[48]=new String("Minor");
		TT[61]=new String("Bool");
		TT[51]=new String("Result");
		TT[5]=new String("Com_Cp");
		TT[42]=new String("Minus");
		TT[14]=new String("Com_Ls");
		TT[27]=new String("Where");
		TT[25]=new String("Criteria");
		TT[43]=new String("Plus");
		TT[59]=new String("GMA");
		TT[15]=new String("Com_Str");
		TT[28]=new String("Prep_supp");
	}
public String getTT(int i){return TT[i];}
}
