#!/bin/tcsh -f
set path =($path . /usr/bin/jvm/jdk1.7.0/bin /home/robizz/gitRepo/Linguaggi_Traduttori\ fork\ da\ jo/drawTree/cup/java_cup/ )
setenv CLASSPATH .:/home/robizz/gitRepo/Linguaggi_Traduttori\ fork\ da\ jo/drawTree/cup

