#!/bin/tcsh -f
set path =($path . /usr/bin/jvm/jdk1.7.0/bin /home/jo/tooljava/jflex-1.4.1/bin/ /usr/bin/jvm/jdk1.7.0/bin /home/jo/gitRepo/Linguaggi_Traduttori\ fork\ da\ jo/drawTree/cup/java_cup/ /home/jo/tooljava/cup/java_cup/)
setenv CLASSPATH .:/home/jo/POLITO/Linguaggi_Traduttori/drawTree/cup

