#!/bin/tcsh -f
set path =($path . /usr/bin/jvm/jdk1.7.0/bin /home/jo/POLITO/Linguaggi_Traduttori/cup/java_cup/ )
setenv CLASSPATH .:/home/jo/POLITO/Linguaggi_Traduttori/generated/it/polito/lt/skype/generated/parser/cup

